import axios from "axios";
import { useRouter } from "next/router";
import { useState } from "react";
import Head from 'next/head'

const Login = () => {
  const [username, setUsername] = useState(null);
  const [password, setPassword] = useState(null);
  const [error, setError] = useState(false);
  const router = useRouter();

  const handleClick = async () => {
    try {
      await axios.post("https://breeze-res.vercel.app/api/login", {
        username,
        password,
      });
      router.push("/admin");
    } catch (err) {
      console.log(err);
      setError(true);
    }
  };

  return (
    <div className="min-h-[100vh] bg-gray-200 flex justify-center items-center">
      <Head>
        <title>Breeze Burger</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/imgs/ico.png" />
        <link href="https://unpkg.com/aos@2.3.1/dist/aos.css" rel="stylesheet"></link>
        <meta charSet='utf-8' />
      </Head>
      <div >
        <div className='w-[100%] text-center mb-10'>
          <span className="font-capriola text-[30px] text-blue-900">Admin  <span className='text-green-600'>Dashboard</span></span>
        </div>
        <div className="flex flex-col gap-4 item-center">
          <input
          placeholder="username"
          className="border-2 border-green-600 px-3 py-2 rounded-lg focus:outline-none focus:ring-1 focus:ring-green-600 "
          onChange={(e) => setUsername(e.target.value)}
        />
        <input
          placeholder="password"
          type="password"
          className="border-2 border-green-600 px-3 py-2 rounded-lg focus:outline-none focus:ring-1 focus:ring-green-600 "
          onChange={(e) => setPassword(e.target.value)}
        />
        <button className="px-4 py-1 bg-green-600 rounded-md w-fit text-white" onClick={handleClick} >
          Sign In
        </button>
        {error && <span className="text-red-600">Wrong Credentials!</span>}
        </div>
        
      </div>
    </div>
  );
};

export default Login;