import React, { useState } from 'react';
import styles from '../styles/Cart.module.css';
import Image from 'next/legacy/image';
import { useSelector, useDispatch } from 'react-redux';
import { removeProduct, updateCart, reset } from '../redux/cartSlice';
import axios from 'axios';
import { useRouter } from "next/router";
import OrderDetail from "../components/OrderDetail";
import Head from 'next/head'
import Powered from '@/components/Poweredlatest';


const Cart = () =>{
  const cart = useSelector((state) => state.cart);
  const [open, setOpen] = useState(true);
  const [cash, setCash] = useState(false);
  const dispatch = useDispatch();
  const router = useRouter();


  const createOrder = async (data) => {
    try {
      const res = await axios.post('https://]breeze-res.vercel.app/api/orders', data);
      if (res.status === 201) {
        dispatch(reset());
        router.push(`/orders/${res.data._id}`);
        console.log(data)
      }
    } catch (err) {
      console.log(err);
    }
  };

  const handleRemove = (productId) => {
    dispatch(removeProduct(productId));
  };

  
  return (
    <>
    <div className="bg-gray-200 px-4  pt-[20vh] min-h-screen w-screen text-sm md:text-base">
      <Head>
        <title>Smash Burger</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/imgs/ico.png" />
        <link href="https://unpkg.com/aos@2.3.1/dist/aos.css" rel="stylesheet"></link>
        <meta charSet='utf-8' />
      </Head>
      <div className=" overflow-auto scrollbar">
        <table className="basic">
          <thead className=''>
            <tr className="">
              <th>Product</th>
              <th className='min-w-[150px]'>Name</th>
              <th className='min-w-[150px]'>Extras</th>
              <th className='min-w-[60px]'>Price</th>
              <th>Quantity</th>
              <th>Delete</th>
            </tr>
          </thead>
          <tbody>
            {cart.products.map((product, size) => (
              <tr className="text-blue-900" key={product._id}>
                <td className="">
                  <div className="">
                    <Image
                      src={product.img}
                      width={50}
                      height={50}
                      objectFit="cover"
                      alt=""
                    />
                  </div>
                </td>
                <td>
                  <span className="text-blue-900">{product.size.text} {product.title}</span>
                </td>
                <td>
                  <span className="">
                    {product.extras.map((extra) => (
                      <span key={extra._id}>{extra.text}, </span>
                    ))}
                  </span>
                </td>
                <td>
                  <span className="">{product.price} £ </span>
                </td>
                <td>
                  <span className="">{product.quantity}</span>
                </td>
                <td className=''>
                  <button
                    className="bg-red-700 text-white px-2 py-1 rounded-md"
                    onClick={() => handleRemove(product._id)}
                  >
                    Remove
                  </button>
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
      <div className="mt-16 text-blue-900  ">
        <div className="bg-white min-w-[230px] max-w-[400px] rounded-md py-5 px-3 h-[180px] flex flex-col justify-evenly">
          <h2 className="font-capriola text-[30px] text-blue-900 text-center">CART TOTAL</h2>
          <div className="text-lg font-bold">
            <b className="font-capriola">Total: </b>{cart.total} £ 
          </div>
          {open &&
            <div className={styles.paymentMethods}>
              <button
                className="text-white bg-blue-900 rounded-md w-fit px-4 py-1"
                style={{ width: "100%" }}
                onClick={() => setCash(true)}
              >
              CASH ON DELIVERY
              </button>
                </div>
              }
                </div>
              </div>
      
              {cash && <OrderDetail total={cart.total} setCash={setCash} createOrder={createOrder} quantity={cart.products.map((product) => (product.quantity))} extra={cart.products.map((product) => (product.extras.map((extra) => (
                     extra.text
                    ))))} title={cart.products.map((product) => (product.title))} size={cart.products.map((product) => (product.size.text))} />}


              </div>
              </>

  );
};

export default Cart;